### ISSUE TITLE
회원 & 채널 API 수정 사항

### ISSUE THREAD

**Issue by srngch** [team-noir/the-pong#271]
## Tasks

- [x] 변수명 수정: res body의 `rank`를  `level`로
  - GET `/api/v1/my/whoami`
  - GET `/api/v1/users/:userId`
  - GET `/api/v1/users`
- [x] 응답 내용 삭제: `achievements: []`, `games: []` 제거하기
  - GET `/api/v1/users/:userId`
  - GET `/api/v1/users`
- [x] endpoint path 수정
  - DELETE `/api/v1/channels/:channelId` -> DELETE `/api/v1/channels/:channelId/users`
    - 채널이 삭제되는 것이 아니라, 채널에 참여한 유저를 삭제하는 것이기 때문에
- [x] endpoint method 수정 `/api/v1/channels/:channelId`
  - POST -> PUT 
    - 채널이 생성되는 것이 아니라, 이미 생성된 채널의 참여자 목록을 수정하는 것이기 때문에

--- 

- merge하면 프론트도 같이 수정되어야하니까 PR에 프론트 리뷰어 지정 부탁드립니다
