### ISSUE TITLE
스타일링 적용

### ISSUE THREAD

**Issue by srngch** [team-noir/the-pong#278]
## Tasks

- [x] 온보딩
- [x] 팔로잉
- [x] 설정
- [x] 설정 - 프로필 수정
- [x] 설정 - 2FA
- [x] 설정 - 차단 관리
- [x] 프로필
- [x] 새 채널 만들기
- [x] 채널
- [x] ProfileImage 컴포넌트 비율 문제
