### ISSUE TITLE
게임 플레이 중 발생되는 문제

### ISSUE THREAD

**Issue by PCHANUL** [team-noir/the-pong#385]
## 구현할 내용

두 클라이언트가 연결되어 게임을 하는 도중에 발생되는 문제 

## Tasks

- [x] owner가 게임을 시작하지만 player는 화면에 game start가 사라지지 않는다.
- [x] 한 라운드가 종료된 후 게임이 다시 시작되지 않는다.
- [x] 게임 결과를 클라이언트에서 받지 못한다.
- [x] 게임 결과 요청 중복이 가능하다.
- [x] 게임 라운드 도중에 유저가 나가도 게임이 종료되지 않는다.

**Comment by hhkim0729** [comment]
- [ ] 관전자가 나갔다가 다시 들어오려고 해도 409 에러

**Comment by PCHANUL** [comment]
> - [ ] 관전자가 나갔다가 다시 들어오려고 해도 409 에러
> 
> 

#501 이슈에서 해결합니다.
