### ISSUE TITLE
게임 플레이 중 발생되는 문제

### ISSUE THREAD

**Issue by PCHANUL** [team-noir/the-pong#386]
## Tasks

- [x] 게임이 시작되었을때 player의 video 배경화면이 검정입니다.
- [x] 라운드 종료 후 점수가 업데이트되지 않습니다.

- [x] rtc가 연결되면 owner는 count를 변경하지만 다른 player는 count를 변경하지 못합니다.
임시로 rtcGetOffer 마지막에 인터벌을 시작시켜서 해결했습니다.
```js
// line 150
if (isPlaying) return;
interval.current = setInterval(
  () => setCount((prevState) => prevState - 1),
  1000
);
```
