### ISSUE TITLE
서버 이미지 파일 유효성 검사

### ISSUE THREAD

**Issue by srngch** [team-noir/the-pong#455]
## 구현할 내용

프로필 이미지 받는 부분

## Tasks

- [x] 파일의 개수가 하나인지
- [x] 파일 종류가 이미지 파일인지
- [x] 파일 사이즈는 자동으로 되는 것 같은데, 다시 체크해보기
- [x] nginx 최대 파일 용량 수정하기 -> 1MB로 유지

**Comment by srngch** [comment]
파일 큰 경우 nginx단에서 [413](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413) 리턴
